version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    ports:
      - "8083:8080"
    networks:
      - envoymesh

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - envoymesh

  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    networks:
      - envoymesh

  auth:
    image: thiva-auth:latest
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/auth:/kieker/logs/
    networks:
      - envoymesh

  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    ports:
      - "8086:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    networks:
      - envoymesh

  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    ports:
      - "8087:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    networks:
      - envoymesh

  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    networks:
      - envoymesh
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - envoymesh

networks:
  envoymesh: {}
